connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://34.35.110.117:5432/dhis2
connection.username = dhis2_app
connection.password = Password1!

tracker.import.preheat.cache.enabled=off

server.https = off
