connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql:///dhis2?cloudSqlInstance=project-16612860-7367-4485-880:africa-south1:dhis2&socketFactory=com.google.cloud.sql.postgres.SocketFactory
connection.username = dhis2_app
connection.password = ${DB_PASSWORD}

tracker.import.preheat.cache.enabled=off

server.https = off
